-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Gép: 127.0.0.1
-- Létrehozás ideje: 2025. Ápr 05. 12:12
-- Kiszolgáló verziója: 10.4.32-MariaDB
-- PHP verzió: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Adatbázis: `stephen_king`
--

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `konyv`
--

CREATE TABLE `konyv` (
  `konyv_id` int(11) NOT NULL,
  `konyv_cim` varchar(255) NOT NULL,
  `konyv_kep` varchar(255) NOT NULL,
  `konyv_leiras` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_hungarian_ci;

--
-- A tábla adatainak kiíratása `konyv`
--

INSERT INTO `konyv` (`konyv_id`, `konyv_cim`, `konyv_kep`, `konyv_leiras`) VALUES
(1, 'Holly', 'kep1.jpg', 'Nyolc évvel Mr. Mercedes tömeggyilkossága után Holly Gibney kollégájával, Pete Huntley-val vezeti a Becsületes Megtaláló Nyomozóirodát. Többnyire eltűnt kutyákat, macskákat és óvadékszökevényeket kerestetnek velük. Amikor Penny Dahl segítséget kér tőlük lánya eltűnése miatt, Holly csak vonakodva vállalja el az ügyet. A társa, Pete covidos. Bonyolult lelkivilágú anyja pedig éppen most halt meg. Hollynak inkább szabadságra kellene mennie. Azonban van valami Penny Dahl kétségbeesett hangjában, ami miatt a nyomozónő képtelen nemet mondani.\r\n\r\nBonnie Dahl eltűnésének helyszínétől néhány sarokra él Rodney és Emily Harris. Mindketten egyetemi tanárok, ők a polgári értékek megtestesítői: nyolcvanas házaspár, még mindig odavannak egymásért, és egyetemi karrierjük végén aktív nyugdíjas éveiket töltik. Azonban mutatós, könyvekkel teli házuk alagsorában szörnyű titkot rejtegetnek, amelynek Bonnie eltűnéséhez is köze lehet. Azt, hogy mit művelnek, a lehetetlenséggel határos kideríteni: mindketten rafináltak, türelmesek és könyörtelenek.\r\n\r\nStephen King új, hátborzongató mesterművében Hollynak minden képességét latba kell vetnie, hogy elméletben és gyakorlatban is meg tudja előzni egy lépéssel a két, ijesztően eltorzult gondolkodású professzort.'),
(2, 'Éjszakai műszak', 'kep2.jpg', '\"...nem tudok úgy elaludni, hogy a lábam kilóg a takaró alól. Mert ha egyszer egy hideg kéz kinyúlna az ágy alól és megragadná a bokámat...\" - írja Stephen King e húsz kiváló elbeszélést tartalmazó kötet előszavában.\r\nA félelem - hiába is tagadnánk - mindannyiunk életében jelen van. Emlékezzünk csak vissza gyerekkori mumusainkra, nyomasztó álmainkra, felnőttkori szorongásainkra. Ezek a félelmek olykor megalapozottak, máskor teljesen irracionálisak, néha elmosódottak, máskor határozott alakot öltenek. Szörnyülködünk, borzongunk az újsághíreken, mégis mohón elolvassuk, hogy \"Agyonverte...\", \"Kútba dobta...\", \"Feltrancsírozta...\" stb.\r\nStephen King a maga mesteri és utánozhatatlan módján formába önti, történetekké kerekíti ezeket az érzéseket, csakhogy e teljességgel modern mesékben nem a vasorrú bába, hanem egy megvadult mosodai gőzvasaló üldözi áldozatát, a hétfejű sárkány helyett életre kelt játék hadsereg indít véres bosszúhadjáratot, netán a fűnyíróember ajánlja fel szolgálatait a kertvárosi ház gyanútlan lakóinak, s nem kell az óriások birodalmába látogatni, megteszi egy sivár országúti pihenő, ahol őrjöngő kamionok hajkurásszák a kávéra betérő fáradt utast, Puhaléptű Jackről már nem is szólva...\r\nNos, kedves Olvasó, kucorodjon kedvenc karosszékébe, készítsen maga mellé egy csésze teát, bár olykor egy pohárka feszültségoldó töményebb sem árt (hanem a cigarettával csínján bánjon, mert esetleg meglátogatják a Leszoktató Rt. munkatársai!), és lapozza fel a kötetet. Azért előtte nem árt ellenőrizni - biztos, ami biztos -, hogy jól bezárta-e az ajtót...'),
(3, 'Tündérmese', 'kep3.jpg', 'A legendás történetmondó, Stephen King képzelete legmélyebb kútjába merül alá ebben a varázslatos regényben. A Tündérmese kiválóan ötvözi Óz Smaragdvárosát a Grimm fivérek meséivel és az üveghegyen túl is rettegve hallgatott gótikus rémtörténetekkel. Lenyűgöző esti mese Stephen King jól ismert szórakoztató és félelmetes stílusában.\r\nA legendás történetmondó, Stephen King képzelete legmélyebb kútjába merül alá ebben a varázslatos regényben.\r\nA Tündérmese csodálatos és káprázatos regény, amely megható tisztelgés Lovecraft, Ray Bradbury, C. S. Lewis és a fantasztikum számos más szerzője előtt. Kiválóan ötvözi Óz Smaragdvárosát a Grimm fivérek meséivel és az üveghegyen túl is rettegve hallgatott gótikus rémtörténetekkel. Charlie Reade egy átlagos középiskolás srác, remekül baseballozik, a focicsapat egyik legjobb játékosa, és szorgalmas tanuló. De nagy terhet cipel a vállán. Édesanyja hétéves korában életét vesztette egy autóbalesetben, az apját pedig a gyász és a bánat az ivásba száműzte. A fiúnak túl hamar kellett megtanulnia, hogyan vigyázzon magára - és a lassan felépülő apjára.\r\nÉvekkel később Charlie egy nap találkozik a környékükön élő, egykoron szebb napokat megélt Radar nevű kutyával és magának való, idős gazdájával, Howard Bowditchcsal, mikor megmenti a nagy házában remeteként élő öregembert. A gondoskodó Charlie végül ápolóként marad Mr. Bowditch mellett, és közben nemcsak az idős férfihoz kerül közelebb, hanem teljesen szívébe zárja Radart. Amikor Bowditch váratlanul meghal, Radart és a vagyonát is a fiúra hagyja, valamint egy rejtélyes magnókazettát, amelyen elmeséli különös, senki által nem ismert történetét. És hogy milyen titokzatos világot rejt a zárt fészer a hátsó udvaron. Charlie-nak végül alá kell szállnia a különös országba, hogy megmentse beteg kutyája életét, és megküzdjön e másik világot elátkozó gonosszal.'),
(4, 'Később', 'kep4.jpg', 'Az egyedülálló anya gyermeke, Jamie Conklin csak hétköznapi gyerekkorra vágyik. Jamie azonban nem mindennapi srác. Látja, amit más nem láthat, és megtudhatja azt, amit más nem. Anyja arra buzdítja a természetfeletti erővel született fiát, hogy tartsa titokban a képességét. De amikor a New York-i rendőrség egyik problémás nyomozója bevonja Jamie-t egy sorozatgyilkos üldözésébe, aki a síron túlról is robbantással fenyegetőzik, a fiú szembesül azzal, milyen súlyos árat is kell fizetnie, és kénytelen szembeszállni a gonosz minden formájával.\r\nA Később, akárcsak a Joyland és A coloradói kölyök, a Hard Case Crime sorozat bűnügyi történeteiben jelent meg, és jól bizonyítja, hogy King a kisprózának is igazi nagymestere. A kisregény megható felnövéstörténet, lebilincselő krimi és kísértethistória egyszerre, félelmetes és izgalmas mese az elveszett ártatlanságról és a megpróbáltatásokról, mikor jó és rossz között kell választanunk.'),
(5, 'Minél véresebb', 'kep5.jpg', 'Stephen King legújabb kötetében ezúttal négy lenyűgöző kisregény kapott helyet. A Mr. Harrigan telefonja a fiatal Craig és a magának való, idős Mr. Harrigan barátságát meséli el. Miután a fiú elveszti és eltemeti öreg mentorát, különös üzenetek érkeznek a telefonjára, amelyek végérvényesen megváltoztatják az élét. A Chuck életé-ben a világ összeomlani látszik, az internet leáll, az emberek kétségbeesetten próbálnak túlélni, csak egy bizonyos Chuckot éltetnek a városban mindenfelé. A kötet legformabontóbb és legmeglepőbb írásából megismerhetjük a titokzatos idegen életét. A Minél véresebb kisregényében gyanús körülmények között bomba robban egy iskolában. A híradásokat figyelve Holly Gibney gyanús nyomokat vesz észre és a tettes nyomába ered, miközben fény derül az évek óta lappangó, félelmetes titokra. King ebben az írásában a Mr. Mercedes és A kívülálló világába tér vissza, a folytatásból pedig megtudhatjuk, hogyan alakult a magánnyomozó további élete. A patkány hőse a kiváló novellista, Drew Larson, aki egy váratlan ihlet hatására családja erdei házába vonul, hogy megírja élete első regényét. A munka azonban lassan halad, ráadásul a férfi lázas betegen a hegyen reked egy viharban. Az ítéletidőben végül megment egy patkányt, és a váratlan látogatóval töltött éjszaka után hihetetlen erőre kapva befejezi élete fő művét. A sikernek azonban ára van, és Drew kénytelen szembenézni a következményeivel.\r\nA népszerű és legendás szerző csodálatos karrierje során újra és újra visszatér a rövidebb lélegzetvételű művekhez, és bizonyítja, hogy mind a mai napig képes különleges alkotásokkal meglepni olvasóját.'),
(6, 'Tortúra', 'kep6.jpg', 'Paul Sheldon sikeríró, a szépkeblű közönség bálványa befejezi legújabb és legjobb regényét, aminek örömére jól beiszik, és kábán autóba vágja magát. Egy veszélyes útkanyarban utoléri az észak-amerikai Sziklás-hegységben nem ritka hóvihar. Isten háta mögötti, magányos tanyaházából bevásárolni indul kisteherautóján Annie Wilkes, a Sheldon-regények könnyes rajongója. Az árokba borult autóroncsban kedvenc szerzőjére ismer, akinek összetört testében alig pislákol az élet. Kihúzza az árokból. Hazaviszi. Életre kelti. Új Sheldon-regényt akar. Csak magának.'),
(7, 'A kívülálló', 'kep7.jpg', 'A Mr. Mercedes - Aki kapja, marja - Agykontroll trilógia után Stephen King - vagy ahogy rajongói világszerte emlegetik: a Mester - ismét egy hátborzongató thrillerrel hozza rá olvasóira az álmatlanságot.\r\nAz oklahomai kisváros, Flint City egyik parkjában brutálisan megerőszakolt, meggyilkolt és megcsonkított holttestre bukkannak. Az áldozat Frank Peterson, egy fehér fiúgyermek, életkora 11 év. A felfoghatatlan tett elkövetője pedig szemtanúk állítása és több, cáfolhatatlan bizonyíték szerint Terry Maitland gimnáziumi irodalomtanár és baseballedző, azaz T. edző, egy mindenki által ismert, köztiszteletben álló ember, két kislány édesapja.\r\nRalph Anderson nyomozó letartóztatja az edzőt, méghozzá a lehető legmegalázóbb módon: a Maitland csapata számára kulcsfontosságú meccs közben, a szurkolósereg szeme láttára. Anderson indulata érthető: az ő kamasz fia is T. edző keze alatt tanulta a sportot.\r\nAz igazságszolgáltatás folyamatában azonban fennakadást okoz, hogy Maitlandnek kikezdhetetlen alibije van: szemtanúk, ujjlenyomatok, sőt DNS-minta igazolják, hogy a gyilkosság idején egy másik, távoli városban tartózkodott. Anderson nyomozónak segítőtársaival együtt választ kell találniuk a kérdésre: hogyan lehet ugyanaz az ember egyszerre két helyen?\r\nA rejtély megoldása Kinghez méltóan egyszerre hihetetlen és kétségbevonhatatlan, bármennyire sokkolja is azokat, akik egy texasi barlang mélyén végül szembekerülnek vele.\r\n\r\nA kívülálló amellett, hogy a New York Times bestsellerlistájának élére került, a Goodreads-en 2018-ban kategóriájának legjobb könyve lett, és az HBO minisorozatot készített belőle.'),
(8, 'Emelkedés', 'kep8.jpg', 'Castle Rock kisvárosában, Stephen King számos ikonikus történetének helyszínén él Scott Carey, az elvált belsőépítész. Monoton mindennapjait leginkább a beérkező munkák mellett a szomszédjába költözött fiatal nőkkel folytatott sikertelen küzdelem töri meg, akiknek a kutyái rendszerint az ő gyepén végzik el a dolgukat. Scott látszólag nem különbözik másoktól, mégis különös dolgok történnek vele. Napról napra egyenletesen veszít a súlyából, és teljesen mindegy, hogy ruhában vagy ruha nélkül, székkel vagy súlyzókkal áll rá a mérlegre, annak nyelve mindig az adott állapotnak megfelelő súlyt mutatja. Scott értetlenül áll a helyzet előtt, de mivel nem akar kísérleti nyúl lenni egy kórházi műtőasztalon, ezért titkáról egyedül barátjának, dr. Bob Ellisnek mesél. Mindeközben a gyepért folytatott harc során kiderül, hogy a szomszédai által működtetett új étterem gondba kerül. Amikor Scott felismeri a nők felé irányuló előítéletet, beleértve a sajátját is, úgy dönt, mindenáron segíteni fog. Scottnak azonban nem marad sok ideje, súlyvesztése felgyorsul, így szembe kell néznie az elkerülhetetlennel: hamarosan nem marad olyan fizikai erő, amely a földön tartsa. A valószínűtlen szövetségek, az éves futóverseny és Scott rejtélyes szenvedése végül közel hozza egymáshoz a feleket, és a legjobbat hozza ki azokból az emberekből, akik eddig csak a rosszat látták egymásban és saját magukban egyaránt. Az Emelkedés különleges mese a megértésről, az elfogadásról és a segítésről. És persze a jelenkor amerikai mindennapjairól. Stephen King mindig meg tudja lepni az olvasóit és képes új oldaláról megmutatkozni. Garantáltan felemeli olvasóját.'),
(9, 'Végítélet', 'kep9.jpg', 'Valahol a kaliforniai sivatag mélyén, egy titkos katonai laboratóriumban üzemzavar támad, s elszabadul egy gyilkos vírus. Az emberiség csupán egy kis csoportja éli túl a kórt. A túlélők két táborra oszlanak: vannak, akik Abagail anyát, a 108 éves idős asszonyt, és vannak, akik a baljós, sötét lényt, Randall Flagget követik. Míg az egyik csoport a társadalom újrafelépítésén fáradozik, a másik fegyverkezik és katonákat képez ki. Hamarosan elkerülhetetlenné válik az összecsapás. Stephen King klasszikussá vált monumentális regénye maga a figyelmeztetés: \"Emberiség, vigyázz!\"'),
(10, 'Carrie', 'kep10.jpg', 'A chamberlaini gimnáziumban közeleg az érettségi. A tizenhat éves, esetlen Carrie White-ot nemcsak bigottan vallásos anyja terrorizálja, hanem diáktársai - főként a lányok - gúnyolódásának is állandó céltáblája. Egy különösen megalázó esemény után a főkolomposokat megbüntetik, Carrie-ben pedig nőttön-nő az indulat, elégtételt akar venni az őt ért sérelmekért. Egyre inkább tudatosul benne, hogy félelmetes telekinetikus képessége micsoda hatalom. Végül elérkezik az érettségi bál estéje, ami felejthetetlen lesz mindenki számára, és örökre megváltoztatja a város életét.\r\n\r\nA Carrie Stephen King sorrendben negyedik regénye, mégis elsőként jelent meg, és zajos sikert aratott: egy év alatt több mint egymillió példányt adtak el belőle. Írója akkoriban még középiskolai tanárként dolgozott, alig jött ki a fizetéséből, és ehhez a történethez nem fűzött komolyabb reményeket - kezdetben novellának szánta, de nem volt vele elégedett. Végül ki is dobta, az anekdota szerint felesége bányászta elő a szemetesből, és ő győzte meg a pályakezdő írót, hogy érdemes kidolgoznia az ötletet. Egy visszaemlékezésben afféle fordított Hamupipőke-történetnek nevezte a Carrie-t, amelyet a Rosemary gyermeke és az Ördögűző című filmekkel állítanak párhuzamba.'),
(11, 'Rémálmok bazára', 'kep11.jpg', 'Harmincöt évvel az Éjszakai műszak című novelláskötete után a hátborzongató történetek nagymestere új elbeszélésgyűjteménnyel lepte meg Hűséges Olvasóit.\r\nA Rémálmok bazára húsz, kötetben korábban nem közölt történetet tartalmaz, s King mindegyikhez rövid bevezetőt írt, amelyben feltárja az írások születésének körülményeit és a maga személyes motivációit.\r\nA történetek között izgalmas kapcsolatok, közös vonások fedezhetők fel: erkölcs, utóélet, bűntudat, mit tennénk másként, ha a jövőbe látnánk vagy éppen kijavíthatnánk a múltban elkövetett hibáinkat. Némelyik novella szereplője az élete végéhez közeledve felidézi bűneit és vétkeit; mások ráébrednek, hogy természetfeletti képességekkel rendelkeznek; és vannak, akik vesztükre egyenesen az ördöggel paktálnak.\r\nKing kirakodóvásárában igazán változatos a kínálat egy autónak látszó szörny ( la Christine), egy ember, aki gyászjelentésekkel gyilkol, egy e-könyv-olvasó, amely párhuzamos világokra nyit ablakot, és persze az örök favorit, az emberiség végpusztulása... Minden olvasó megtalálhatja itt a maga kedvencét de a szerző figyelmeztet, hogy a portékáját óvatosan kell kezelni, mert a legjobbaknak foguk van.'),
(12, 'A halálsoron', 'kep12.jpg', 'A Cold Mountain fegyház E blokkjában, a siralomházban, néhány rab várja, hogy elérkezzen az idő, amikor végig kell mennie a halálsoron, melynek a végén ott magasodik a villamosszék, az Öreg Füstös. Mindnyájukat Eduard Delacroix-t, a keszeg kis franciát, Vad Billy Whartont, az eszelős fiatalembert, és John Coffeyt, a hatalmas termetű, folyvást könnyező négert főbenjáró bűnért, többszörös gyilkosságért ítélték halálra. Paul Edgecombe, a blokk lelkiismeretes főfoglárra azonban bizonyos meglepő, mondhatni, csodás események hatására úgy érzi, néhány dolognak utána kell járnia. Lehet, hogy a három halálraítélt közül az egyik ártatlan? S ha igen, vajon módjában és hatalmában áll-e tennie is valamit ez ügyben? Hisz Paul tudja, milyen óriási kockázatot vállal megbízható munkatársaival együtt, nemcsak az állásukat veszíthetik el, de ők maguk is börtönbe kerülhetnek. Amikor megtudja az igazságot, nincs sok választása.\r\nStephen King letehetetlenül izgalmas, feszes regényéből nagy sikerű film készült Tom Hanks és Michael Clarke Duncan főszereplésével.'),
(13, 'Agykontroll', 'kep13.jpg', 'Bill Hodges, a nyugdíjas zsaru és társa, Holly Gibney egy öngyilkosság ügyében nyomoznak, amelyhez köze lehet Brady Hartsfieldnek, az ördögi Mercedeses Gyilkosnak.\r\nIgaz, Brady öt évvel azelőtt, amikor többször is fejbe vágták a zsúfolt koncertcsarnokban, amelyet fel akart robbantani, olyan súlyos agysérülést szenvedett, hogy azóta is kórházban van, csak üresen bambul, és az orvosok szerint reménye sincs a gyógyulásra. Ám a 217-es szobában, ahol az ártalmatlannak tartott gyilkos vegetál, egy titokzatos, gonosz erő ébred, amely hozzásegítheti Bradyt, hogy bosszút álljon ellenségein - sőt az egész városon...\r\nA Mr. Mercedes és az Aki kapja, marja után itt a Bill Hodges-trilógia csattanós fináléja, amelyben a hősöknek immár egy természetfölötti képességgel rendelkező, sátáni alakkal kell megküzdeniük életre-halálra.'),
(14, 'A ragyogás', 'kep14.jpg', '\"- Minden nagy szállodának vannak botrányai - mondta. - Ahogy kísértet is van minden nagy szállodában. Hogy miért? A fenébe is, az emberek jönnek-mennek. Megesik, hogy valamelyik a szobájában dobja fel a talpát, a szíve, vagy gutaütés, vagy valami ilyesmi. A szálloda babonás hely. Nincs tizenharmadik emelet, nincs tizenhármas szoba, nincs tükör az ajtón, amin az ember bemegy, meg hasonlók.\"\r\n\r\nStephen King egyik leghíresebb története, A ragyogás, a Sziklás-hegység egyik magaslatán, egy világtól elzárt szállodában játszódik. Itt vállal állást az alkoholizmusából éppen kigyógyult Jack Torrance, és vele együtt ideköltözik felesége, Wendy, és kisfia, Danny is. Miközben Jack egyre megszállottabban próbálja megírni a szálloda történetét, természetfeletti, látnoki képességekkel rendelkező fia egyre több furcsa jelet lát...\r\n\r\nA ragyogás 1977-ben jelent meg először, és azonnal bestseller lett. Az azóta klasszikussá vált műből 1980-ban Stanley Kubrick rendezett filmet, Jack Nicholson főszereplésével.'),
(15, 'Álom doktor', 'kep15.jpg', '- Tudom, mit szeretnél, cukorfalat. Gyere vissza, és megkaphatod.\r\n- Száját közelítette Andiéhoz, nyelvével addig simogatva annak felső ajkát, amíg az köddé nem foszlott. A szeme azonban kitartott, s Rose tekintetébe kapcsolódott.\r\n- Sabbatha hanti - danolta a kórus. - Lodsam hanti. Cahanna risone hanti.\r\nAndi visszajött, kimeredő, fájdalmas szeme köré megképződött az arc, melyet aztán a test is követett. Rose egy pillanatig látta karcsontjait és az ő ujjait szorító ujjakéit, majd ismét rájuk nőtt a hús.\r\nRose újból megcsókolta. Andi még kínjai között is reagált, Rose pedig a fiatalabb nő torkába lehelte saját lényegét.\r\nKell nekem ez a nő. És ami kell nekem, azt meg is kapom.\r\nAndi újra lenullázódóban volt, de Rose érezte, hogy küzd ellene, és felülkerekedik. A tüdejébe szívott, jajongó életerőből táplálékot merített, ahelyett hogy megpróbálta volna eltaszítani.\r\nSzuflát gyűjtött - most először.\r\n\r\nA ragyogás folytatásában a gonosz ismét visszatér közénk. A kisfiú, aki annak idején annyi rémséget élt át a Panoráma Szállóban, immár felnőttként, miután kigyógyult alkoholbetegségéből, egy New Hampshire-i hospice-házban dolgozik ápolóként, ahol a betegek Álom doktornak kezdik szólítani. Dan Torrance különleges képessége felnőttkorában is fontos szerephez jut. Régóta kísértő szellemek, az Igaz Kötés nevű baljós, vándorló kompánia és egy Abra nevű, még Danénél is erősebb ragyogással bíró kislány körül bonyolódik a lidérces, borzongató történet.'),
(16, 'Borzalmak városa', 'kep16.jpg', 'Ben Mears, a sikeres író visszatér a Jerusalem\'s Lot nevű, isten háta mögötti kisvárosba, hogy \"kiírja\" magából itt szerzett gyermekkori traumáját: az 1930-as években a komoran a helység fölé magasodó Marsten-házba vonult vissza egy véres kezű gengszter, aki egy nap - látszólag minden indok nélkül - agyonlőtte feleségét, majd felkötötte magát. A gyermek Ben Mears egyszer beszökött ide, és meglátta a gengszter lógó hulláját, amely még évtizedek múltán sem indult oszlásnak... Az írónak azonban nem a nyugodt alkotómunka jut osztályrészül. Az álmos kisvárost mindinkább a megmagyarázhatatlan rettegés keríti hatalmába. Találnak egy akasztott kutyát, eltűnik két gyerek, s egyik este egy talpraesett kisfiú, Mark Pétrie a szobája ablakában megpillantja az egyik - időközben eltemetett - gyermek vigyorgó arcát. Mark már-már enged a kísértet bűverejének, de azután egy keresztet tart feléje, aminek láttán a jelenés agonizálni kezd, és füstté válik. Ben, Mark és még néhány, mindenre elszánt helybéli megindítja élet-halál harcát a Marsten-ház titokzatos lakói ellen.\r\nA Borzalmak városa Stephen King másodikként megjelent regénye, 1975-ből. Bár a művet a Carrie című regény után adták ki, de előbb született.'),
(17, 'AZ', 'kep17.jpg', 'Heten voltak. Hét kiskamasz barát, akiknek szembe kellett szállniuk a városukat terrorizáló rémmel. A csatornákban, a lefolyókban, a kanálisban lakó Az időről időre felszínre bukkant, és akkor útját hullák szegélyezték. Sok hulla. De Derry városában ezen senki sem lepődött meg. Az emberek halandóak, a gyerekek meg főleg. Egészen addig, amíg ők heten össze nem fogtak, hogy legyőzzék Azt. Bill, a vezér, aki az öccse halálát akarja megbosszulni. Ben, akinek a könyvek a barátai, na meg az ennivaló. Richie, akinek mindig rosszkor jár a szája, ráadásul különféle Hangokon. Stan, aki gyűlöli a rendetlenséget és a piszkot. Eddie, akinek asztmája van és tankszerű anyja. Michael, a néger. És Beverly, a lány, akit ver az apja és akibe ketten is szerelmesek. De hogyan szállhat szembe hét gyerek az egész várost megfertőző gonosszal? Stephen King hatalmas regénye vérfagyasztó izgalmak során válaszolja meg a kérdést. És mesél még gyerekkorról és felnőttségről, pénzről és szegénységről, barátságról és kirekesztettségről, lányról és fiúról. Szóval az életről.'),
(18, 'A búra alatt', 'kep18.jpg', 'Egy teljesen átlagos, gyönyörű őszi napon a békés maine-i Chester\'s Mill kisvárosát váratlanul, a derült égből egy láthatatlan erőtér zárja el a világ többi részétől. A hirtelen alászálló \"búrába\" belecsapódik egy repülőgép és lángoló roncsokban zuhan le az égből, egy kertészkedő asszony keze leszakad, a szomszédos városban dolgozó emberek nem tudnak hazajutni. Senki sem érti, mi ez a megmagyarázhatatlan jelenség, honnan jött, és mikor tűnik el, ha egyáltalán. Aztán ahogy az emberek lassan felfogják, hogy a láthatatlan, de nagyon is valóságos akadály ott van és ott marad, az is kiderül, számukra, hogy Chester\'s Mill nem is olyan békés hely.\r\nDale Barbara, a városban rekedt iraki veterán és alkalmi szakács az események közepén találja magát. Néhány rettenthetetlen ottani lakóval - a helyi újság tulajdonosával, Julia Shumwayjel, két lelkésszel, egy kórházi asszisztenssel, egy anyával és három bátor gyerekkel - kénytelen szembeszállni a város vezetését átvevő Big Jim Rennie-vel, aki még a gyilkosságtól sem riad vissza annak érdekében, hogy kézben tartsa a gyeplőt. Mindeközben a politikus erőszakos fia szörnyű titkokat őriz egy ház sötét kamrájában. De nincs mód elmenekülni a városból, az idő és a levegő pedig egyre kevesebb...'),
(19, 'Cujo', 'kep19.jpg', 'Cujónak hívják Brett Camber legjobb pajtását, az irdatlan méretű, ám jámbor és barátságos bernáthegyit. Cujo szívesen hajkurássza a vadnyulakat a napsütötte mezőn. Nyúl után szaglászik most is, zsákmánya azonban egy üregbe menekül előle, amelyben veszettséggel fertőzött denevérek tanyáznak. A kutya bedugja busa fejét, és egy denevér megmarja az orrát…\r\nCujo szörnyű alak- és személyiségváltozása, ámokfutása merő iszonyattá változtatja Castle Rock lakóinak életét. Maga a Gonosz jött el a városkába, hogy minden vétket megtoroljon, s áldozatul esik neki bűnös és ártatlan egyaránt…\r\nStephen King a tőle megszokott módon, mesterien adagolja-fokozza a feszültséget és a borzalmat – a figyelme egy percig sem lankadhat, Kedves Olvasó!'),
(20, 'Alvajárók', 'kep20.jpg', 'A The New York Times Book Review az év 10 legjobb könyve közé választotta Az alvajárók: Clark történész lebilincselő beszámolója az I. világháború robbanásszerű kezdeteiről. Clark új tudományos eredményekre támaszkodva új szemszögből vizsgálja az I. világháborút, és nem magára a háború csatáira és atrocitásaira, hanem azokra az összetett eseményekre és kapcsolatokra összpontosít, amelyek jószándékú vezetők egy csoportját a brutális konfliktusba vezették. Clark percről percre követi nyomon a háborúhoz vezető utakat egy percről percre, akciódús elbeszélésben, amely Bécs, Berlin, Szentpétervár, Párizs, London és Belgrád kulcsfontosságú döntési központjai között váltakozik, és megvizsgálja az 1914-es eseményeket megalapozó évtizedes történelmet, valamint részletezi azokat a kölcsönös félreértéseket és nem szándékos jelzéseket, amelyek néhány rövid hét alatt előrevitték a válságot. Christopher Clark aprólékosan kutatott és mesterien megírt Az alvajárók című könyve drámai és hiteles krónikája annak, hogyan süllyedt Európa a világot szétszakító háborúba.');

--
-- Indexek a kiírt táblákhoz
--

--
-- A tábla indexei `konyv`
--
ALTER TABLE `konyv`
  ADD PRIMARY KEY (`konyv_id`);

--
-- A kiírt táblák AUTO_INCREMENT értéke
--

--
-- AUTO_INCREMENT a táblához `konyv`
--
ALTER TABLE `konyv`
  MODIFY `konyv_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
